version: '3'
services:
  nginx:
    build:
      dockerfile: ./.docker/nginx/Dockerfile
      context: .
    image: registry.mobbtech.com/cd/hive/nginx:${NGINX_SERVICE_IMAGE_TAG:-current}
    environment:
      FAST_CGI_PASS_ADDRESS: phpfpm
    ports:
      - '80:80'
    volumes:
      - ./web:/usr/src/web
    depends_on:
      - phpfpm
  phpfpm:
    build:
      dockerfile: ./.docker/php/Dockerfile
      context: .
    image: php:7.4.1-fpm
    environment:
      YII_ENV: dev
      YII_DEBUG: 1
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_DB: one
      DATABASE_USER: one
      DATABASE_PASSWORD: one
      PHP_MEMORY_LIMIT: 536870912
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    volumes:
      - .:/usr/src
      - /usr/src/vendor
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    ports:
      - '5432:5432'
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: one
      POSTGRES_USER: one
      POSTGRES_PASSWORD: one
  selenium:
    image: selenium/standalone-chrome:3.14.0
    shm_size: "8g"
    depends_on:
      - nginx